INSERT INTO acc.gl_account (code, major, sub, detail, account_type, tax_category, status)
VALUES
-- Central and bank accounts
('account:bgm',                   'account', 'bgm',             NULL,            'asset',      NULL,        'active'),
('account:cash',                  'account', 'cash',            NULL,            'asset',      NULL,        'active'),
('account:csb',                   'account', 'csb',             NULL,            'asset',      NULL,        'active'),
('account:debit',                 'account', 'debit',           NULL,            'asset',      NULL,        'active'),
('account:medical',               'account', 'medical',         NULL,            'asset',      NULL,        'active'),
('account:mhb',                   'account', 'mhb',             NULL,            'asset',      NULL,        'active'),
('account:tax',                   'account', 'tax',             NULL,            'asset',      NULL,        'active'),
-- Asset accounts (properties)
('asset:711pine',                 'asset',   '711pine',         NULL,            'asset',      'property',  'active'),
('asset:819helen',                'asset',   '819helen',        NULL,            'asset',      'property',  'active'),
('asset:905brown',                'asset',   '905brown',        NULL,            'asset',      'property',  'active'),
-- Unit split accounts for 711pine duplex
('mhb:income:rent:711pine-01',    'mhb',     'income',          'rent:711pine-01', 'income',    NULL,        'active'),
('mhb:income:rent:711pine-02',    'mhb',     'income',          'rent:711pine-02', 'income',    NULL,        'active'),
('mhb:maintenance:711pine-01',    'mhb',     'maintenance',     '711pine-01',    'expense',    'property',  'active'),
('mhb:maintenance:711pine-02',    'mhb',     'maintenance',     '711pine-02',    'expense',    'property',  'active'),
('mhb:tax:711pine-01',            'mhb',     'tax',             '711pine-01',    'expense',    'property',  'active'),
('mhb:tax:711pine-02',            'mhb',     'tax',             '711pine-02',    'expense',    'property',  'active'),
('mhb:insurance:711pine-01',      'mhb',     'insurance',       '711pine-01',    'expense',    'property',  'active'),
('mhb:insurance:711pine-02',      'mhb',     'insurance',       '711pine-02',    'expense',    'property',  'active'),
('mhb:mortgage:711pine-01',       'mhb',     'mortgage',        '711pine-01',    'expense',    'property',  'active'),
('mhb:mortgage:711pine-02',       'mhb',     'mortgage',        '711pine-02',    'expense',    'property',  'active'),
('mhb:utility:gas:711pine-01',    'mhb',     'utility',         'gas:711pine-01',    'expense', 'property',  'active'),
('mhb:utility:gas:711pine-02',    'mhb',     'utility',         'gas:711pine-02',    'expense', 'property',  'active'),
('mhb:utility:water:711pine-01',  'mhb',     'utility',         'water:711pine-01',  'expense', 'property',  'active'),
('mhb:utility:water:711pine-02',  'mhb',     'utility',         'water:711pine-02',  'expense', 'property',  'active'),
('mhb:utility:electric:711pine-01','mhb',    'utility',         'electric:711pine-01','expense','property',  'active'),
('mhb:utility:electric:711pine-02','mhb',    'utility',         'electric:711pine-02','expense','property',  'active'),
('mhb:improvement:711pine-01',    'mhb',     'improvement',     '711pine-01',    'expense',    'property',  'active'),
('mhb:improvement:711pine-02',    'mhb',     'improvement',     '711pine-02',    'expense',    'property',  'active'),
-- Remainder of your GL accounts list
('auto:gas',                      'auto',    'gas',             NULL,            'expense',    'deductible','active'),
('auto:maintenance',              'auto',    'maintenance',     NULL,            'expense',    'deductible','active'),
('bank:fee',                      'bank',    'fee',             NULL,            'expense',    'deductible','active'),
('bgm:ar',                        'bgm',     'ar',              NULL,            'asset',      NULL,        'active'),
('bgm:charity',                   'bgm',     'charity',         NULL,            'expense',    'deductible','active'),
('bgm:equipment:software:license','bgm',     'equipment',       'software:license','expense',  'deductible','active'),
('bgm:fbreen',                    'bgm',     'fbreen',          NULL,            'expense',    'deductible','active'),
('bgm:internet:webmeeting',       'bgm',     'internet',        'webmeeting',    'expense',    'deductible','active'),
('bgm:internet:website',          'bgm',     'internet',        'website',       'expense',    'deductible','active'),
('bgm:mbreen',                    'bgm',     'mbreen',          NULL,            'expense',    'deductible','active'),
('bgm:mcbreen',                   'bgm',     'mcbreen',         NULL,            'expense',    'deductible','active'),
('bgm:prof:training',             'bgm',     'prof',            'training',      'expense',    'deductible','active'),
('bgm:proj exp:dining',           'bgm',     'proj exp',        'dining',        'expense',    'deductible','active'),
('bgm:proj exp:equipment',        'bgm',     'proj exp',        'equipment',     'expense',    'deductible','active'),
('bgm:proj exp:gas',              'bgm',     'proj exp',        'gas',           'expense',    'deductible','active'),
('bgm:proj exp:lodging',          'bgm',     'proj exp',        'lodging',       'expense',    'deductible','active'),
('bgm:rebate',                    'bgm',     'rebate',          NULL,            'income',     NULL,        'active'),
('bgm:sub:geode',                 'bgm',     'sub',             'geode',         'expense',    NULL,        'active'),
('bgm:sub:laboratory',            'bgm',     'sub',             'laboratory',    'expense',    NULL,        'active'),
('credit:usaamc',                 'credit',  'usaamc',          NULL,            'liability',  NULL,        'active'),
('equipment:computer',            'equipment','computer',       NULL,            'asset',      NULL,        'active'),
('escrow:dispersement:891helen',  'escrow',  'dispersement',    '891helen',      'asset',      NULL,        'active'),
('fbreen:tuition',                'fbreen',  'tuition',         NULL,            'expense',    'education','active'),
('insurance:auto',                'insurance','auto',           NULL,            'expense',    NULL,        'active'),
('insurance:health',              'insurance','health',         NULL,            'expense',    NULL,        'active'),
('insurance:life:fb',             'insurance','life',           'fb',            'expense',    NULL,        'active'),
('internet:website',              'internet', 'website',        NULL,            'expense',    NULL,        'active'),
('loan:nissan',                   'loan',    'nissan',          NULL,            'liability',  NULL,        'active'),
('loan:unsecured',                'loan',    'unsecured',       NULL,            'liability',  NULL,        'active'),
('mhb:accountant',                'mhb',     'accountant',      NULL,            'expense',    'deductible','active'),
('mhb:equipment',                 'mhb',     'equipment',       NULL,            'expense',    'deductible','active'),
('mhb:fbreen',                    'mhb',     'fbreen',          NULL,            'expense',    'deductible','active'),
('mhb:income:reimbursement',      'mhb',     'income',          'reimbursement', 'income',     NULL,        'active'),
('mhb:income:rent:819helen',      'mhb',     'income',          'rent:819helen', 'income',     NULL,        'active'),
('mhb:income:rent:905brown',      'mhb',     'income',          'rent:905brown', 'income',     NULL,        'active'),
('mhb:income:sale:baird',         'mhb',     'income',          'sale:baird',    'income',     NULL,        'active'),
('mhb:legal',                     'mhb',     'legal',           NULL,            'expense',    NULL,        'active'),
('mhb:maintenance:905brown',      'mhb',     'maintenance',     '905brown',      'expense',    'property',  'active'),
('mhb:maintenance:disposal',      'mhb',     'maintenance',     'disposal',      'expense',    'property',  'active'),
('mhb:maintenance:snow removal',  'mhb',     'maintenance',     'snow removal',  'expense',    'property',  'active'),
('mhb:mbreen',                    'mhb',     'mbreen',          NULL,            'expense',    NULL,        'active'),
('mhb:mortgage:819helen',         'mhb',     'mortgage',        '819helen',      'expense',    'property',  'active'),
('mhb:mortgage:905brown',         'mhb',     'mortgage',        '905brown',      'expense',    'property',  'active'),
('mhb:pest control:711pine',      'mhb',     'pest control',    '711pine',       'expense',    'property',  'active'),
('mhb:rental registration',       'mhb',     'rental registration', NULL,        'expense',    NULL,        'active'),
('mhb:security deposit',          'mhb',     'security deposit', NULL,           'liability',  NULL,        'active'),
('mhb:security deposit:711pine-01','mhb',    'security deposit', '711pine-01',   'liability',  NULL,        'active'),
('mhb:tax:819helen',              'mhb',     'tax',             '819helen',      'expense',    'property',  'active'),
('mhb:tax:905brown',              'mhb',     'tax',             '905brown',      'expense',    'property',  'active'),
('mhb:tax:baird',                 'mhb',     'tax',             'baird',         'expense',    'property',  'active'),
('mhb:utility:electric:905brown', 'mhb',     'utility',         'electric:905brown','expense', 'property','active'),
('mhb:utility:gas:905brown',      'mhb',     'utility',         'gas:905brown',  'expense',    'property',  'active'),
('mhb:utility:gas:baird',         'mhb',     'utility',         'gas:baird',     'expense',    'property',  'active'),
('mhb:utility:water:905brown',    'mhb',     'utility',         'water:905brown','expense',    'property',  'active'),
('mhb:utility:water:parnell',     'mhb',     'utility',         'water:parnell', 'expense',    'property',  'active'),
('mhb:water heater:711pine-02',   'mhb',     'water heater',     '711pine-02',    'expense',    'property',  'active'),
('mortgage:819helen',             'mortgage','819helen',        NULL,            'liability',  NULL,        'active'),
('mortgage:905brown',             'mortgage','905brown',        NULL,            'liability',  NULL,        'active'),
('mortgage:escrow:dispersement:711pine','mortgage', 'escrow',   'dispersement:711pine','asset', NULL,     'active'),
('mortgage:parnell',              'mortgage','parnell',         NULL,            'liability',  NULL,        'active'),
('mortgage:payment:819helen',     'mortgage','payment',         '819helen',      'liability',  NULL,        'active'),
('mortgage:rate:711pine',         'mortgage','rate',            '711pine',       'liability',  NULL,        'active'),
('nv:air fare',                   'nv',      'air fare',        NULL,            'expense',    'deductible','active'),
('nv:airfare',                    'nv',      'airfare',         NULL,            'expense',    'deductible','active'),
('nv:auto:gas',                   'nv',      'auto',            'gas',           'expense',    'deductible','active'),
('nv:dining',                     'nv',      'dining',          NULL,            'expense',    'deductible','active'),
('nv:lodging',                    'nv',      'lodging',         NULL,            'expense',    'deductible','active'),
('nv:truck rental',               'nv',      'truck rental',    NULL,            'expense',    'deductible','active'),
('personal:cadillac',             'personal','cadillac',        NULL,            'expense',    NULL,        'active'),
('personal:dining',               'personal','dining',          NULL,            'expense',    NULL,        'active'),
('personal:groceries',            'personal','groceries',       NULL,            'expense',    NULL,        'active'),
('personal:household',            'personal','household',       NULL,            'expense',    NULL,        'active'),
('personal:lodging',              'personal','lodging',         NULL,            'expense',    NULL,        'active'),
('personal:movies',               'personal','movies',          NULL,            'expense',    NULL,        'active'),
('proj exp:dining',               'proj exp','dining',          NULL,            'expense',    'deductible','active'),
('proj exp:equipment',            'proj exp','equipment',       NULL,            'expense',    'deductible','active'),
('proj exp:lodging',              'proj exp','lodging',         NULL,            'expense',    'deductible','active'),
('proj exp:meal',                 'proj exp','meal',            NULL,            'expense',    'deductible','active'),
('stmichelle:material',           'stmichelle','material',      NULL,            'expense',     NULL,       'active'),
('telecom:cable',                 'telecom', 'cable',           NULL,            'expense',     NULL,       'active'),
('telecom:cell',                  'telecom', 'cell',            NULL,            'expense',     NULL,       'active'),
('telecom:cell phone',            'telecom', 'cell phone',      NULL,            'expense',     NULL,       'active'),
('tuition:fb4',                   'tuition', 'fb4',             NULL,            'expense',    'education','active'),
('utility:electric:1108parnell',  'utility', 'electric',        '1108parnell',   'expense',     NULL,      'active'),
('utility:gas:1108parnell',       'utility', 'gas',             '1108parnell',   'expense',     NULL,      'active'),
('utility:phone',                 'utility', 'phone',           NULL,            'expense',     NULL,      'active'),
('utility:water:1108parnell',     'utility', 'water',           '1108parnell',   'expense',     NULL,      'active'),
('utility:water:905brown',        'utility', 'water',           '905brown',      'expense',     NULL,      'active'),
('utillity:water:1108parnell',    'utillity','water',           '1108parnell',   'expense',     NULL,      'active');
